name: healthcare_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy>=1.24
  - pandas>=2.0
  - matplotlib>=3.7
  - seaborn>=0.12
  - scikit-learn>=1.3
  - scipy>=1.10
  - dask>=2023.5.0
  - distributed>=2023.5.0
  - hdbscan
  - mlxtend
  - tqdm
  - pyarrow
  - jupyterlab
  - ipykernel
  - kaggle
  - pip:
      - python-dotenv